# ============================================================
# Nginx reverse proxy di depan Node app
# Pattern persis sesuai template yang diminta
# ============================================================
FROM nginx:latest
WORKDIR /etc/nginx/conf.d
RUN rm -rf ./*
COPY ./nginx/nginx.conf /etc/nginx/conf.d/default.conf
EXPOSE 80
ENTRYPOINT ["nginx", "-g", "daemon off;"]
